// Code generated by mockery v1.0.0
package mocks

import mock "github.com/stretchr/testify/mock"

import web "flamingo/framework/web"

// JSONAware is an autogenerated mock type for the JSONAware type
type JSONAware struct {
	mock.Mock
}

// JSON provides a mock function with given fields: data
func (_m *JSONAware) JSON(data interface{}) web.Response {
	ret := _m.Called(data)

	var r0 web.Response
	if rf, ok := ret.Get(0).(func(interface{}) web.Response); ok {
		r0 = rf(data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(web.Response)
		}
	}

	return r0
}
