// Code generated by mockery v1.0.0
package mocks

import context "context"
import mock "github.com/stretchr/testify/mock"
import responder "flamingo.me/flamingo/v3/framework/web/responder"
import web "flamingo.me/flamingo/v3/framework/web"

// RenderAware is an autogenerated mock type for the RenderAware type
type RenderAware struct {
	mock.Mock
}

// Render provides a mock function with given fields: _a0, tpl, data
func (_m *RenderAware) Render(_a0 context.Context, tpl string, data interface{}) web.Response {
	ret := _m.Called(_a0, tpl, data)

	var r0 web.Response
	if rf, ok := ret.Get(0).(func(context.Context, string, interface{}) web.Response); ok {
		r0 = rf(_a0, tpl, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(web.Response)
		}
	}

	return r0
}

// WithStatusCode provides a mock function with given fields: code
func (_m *RenderAware) WithStatusCode(code int) responder.RenderAware {
	ret := _m.Called(code)

	var r0 responder.RenderAware
	if rf, ok := ret.Get(0).(func(int) responder.RenderAware); ok {
		r0 = rf(code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(responder.RenderAware)
		}
	}

	return r0
}
