// Code generated by mockery v1.0.0
package mocks

import event "go.aoe.com/flamingo/framework/event"
import mock "github.com/stretchr/testify/mock"

// Router is an autogenerated mock type for the Router type
type Router struct {
	mock.Mock
}

// Dispatch provides a mock function with given fields: _a0
func (_m *Router) Dispatch(_a0 event.Event) {
	_m.Called(_a0)
}
