// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import context "context"
import mock "github.com/stretchr/testify/mock"

import validator "gopkg.in/go-playground/validator.v9"

// FieldValidator is an autogenerated mock type for the FieldValidator type
type FieldValidator struct {
	mock.Mock
}

// ValidateField provides a mock function with given fields: ctx, fl
func (_m *FieldValidator) ValidateField(ctx context.Context, fl validator.FieldLevel) bool {
	ret := _m.Called(ctx, fl)

	var r0 bool
	if rf, ok := ret.Get(0).(func(context.Context, validator.FieldLevel) bool); ok {
		r0 = rf(ctx, fl)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// ValidatorName provides a mock function with given fields:
func (_m *FieldValidator) ValidatorName() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
