// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import context "context"
import mock "github.com/stretchr/testify/mock"

import validator "gopkg.in/go-playground/validator.v9"

// StructValidator is an autogenerated mock type for the StructValidator type
type StructValidator struct {
	mock.Mock
}

// StructType provides a mock function with given fields:
func (_m *StructValidator) StructType() interface{} {
	ret := _m.Called()

	var r0 interface{}
	if rf, ok := ret.Get(0).(func() interface{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	return r0
}

// ValidateStruct provides a mock function with given fields: ctx, sl
func (_m *StructValidator) ValidateStruct(ctx context.Context, sl validator.StructLevel) {
	_m.Called(ctx, sl)
}
