// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import domain "flamingo.me/flamingo/core/auth/domain"
import mock "github.com/stretchr/testify/mock"

// Store is an autogenerated mock type for the Store type
type Store struct {
	mock.Mock
}

// DestroySessionsForUser provides a mock function with given fields: user
func (_m *Store) DestroySessionsForUser(user domain.User) error {
	ret := _m.Called(user)

	var r0 error
	if rf, ok := ret.Get(0).(func(domain.User) error); ok {
		r0 = rf(user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetHashByUser provides a mock function with given fields: user
func (_m *Store) GetHashByUser(user domain.User) (string, error) {
	ret := _m.Called(user)

	var r0 string
	if rf, ok := ret.Get(0).(func(domain.User) string); ok {
		r0 = rf(user)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(domain.User) error); ok {
		r1 = rf(user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetHashAndSessionIdForUser provides a mock function with given fields: user, hash, id
func (_m *Store) SetHashAndSessionIdForUser(user domain.User, hash string, id string) error {
	ret := _m.Called(user, hash, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(domain.User, string, string) error); ok {
		r0 = rf(user, hash, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
