// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import domain "flamingo.me/flamingo/v3/core/auth/domain"
import mock "github.com/stretchr/testify/mock"
import sessions "github.com/gorilla/sessions"

// Synchronizer is an autogenerated mock type for the Synchronizer type
type Synchronizer struct {
	mock.Mock
}

// Insert provides a mock function with given fields: user, session
func (_m *Synchronizer) Insert(user domain.User, session *sessions.Session) error {
	ret := _m.Called(user, session)

	var r0 error
	if rf, ok := ret.Get(0).(func(domain.User, *sessions.Session) error); ok {
		r0 = rf(user, session)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IsActive provides a mock function with given fields: user, session
func (_m *Synchronizer) IsActive(user domain.User, session *sessions.Session) (bool, error) {
	ret := _m.Called(user, session)

	var r0 bool
	if rf, ok := ret.Get(0).(func(domain.User, *sessions.Session) bool); ok {
		r0 = rf(user, session)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(domain.User, *sessions.Session) error); ok {
		r1 = rf(user, session)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
