// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"flamingo.me/flamingo/v3/framework/web"
	mock "github.com/stretchr/testify/mock"
)

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

type Service_Expecter struct {
	mock *mock.Mock
}

func (_m *Service) EXPECT() *Service_Expecter {
	return &Service_Expecter{mock: &_m.Mock}
}

// AllPermissions provides a mock function for the type Service
func (_mock *Service) AllPermissions(context1 context.Context, session *web.Session) []string {
	ret := _mock.Called(context1, session)

	if len(ret) == 0 {
		panic("no return value specified for AllPermissions")
	}

	var r0 []string
	if returnFunc, ok := ret.Get(0).(func(context.Context, *web.Session) []string); ok {
		r0 = returnFunc(context1, session)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	return r0
}

// Service_AllPermissions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AllPermissions'
type Service_AllPermissions_Call struct {
	*mock.Call
}

// AllPermissions is a helper method to define mock.On call
//   - context1 context.Context
//   - session *web.Session
func (_e *Service_Expecter) AllPermissions(context1 interface{}, session interface{}) *Service_AllPermissions_Call {
	return &Service_AllPermissions_Call{Call: _e.mock.On("AllPermissions", context1, session)}
}

func (_c *Service_AllPermissions_Call) Run(run func(context1 context.Context, session *web.Session)) *Service_AllPermissions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *web.Session
		if args[1] != nil {
			arg1 = args[1].(*web.Session)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Service_AllPermissions_Call) Return(strings []string) *Service_AllPermissions_Call {
	_c.Call.Return(strings)
	return _c
}

func (_c *Service_AllPermissions_Call) RunAndReturn(run func(context1 context.Context, session *web.Session) []string) *Service_AllPermissions_Call {
	_c.Call.Return(run)
	return _c
}
