// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import context "context"
import domain "flamingo.me/flamingo/v3/core/security/domain"
import mock "github.com/stretchr/testify/mock"

import web "flamingo.me/flamingo/v3/framework/web"

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// All provides a mock function with given fields: _a0, _a1
func (_m *Service) All(_a0 context.Context, _a1 *web.Session) []domain.Role {
	ret := _m.Called(_a0, _a1)

	var r0 []domain.Role
	if rf, ok := ret.Get(0).(func(context.Context, *web.Session) []domain.Role); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Role)
		}
	}

	return r0
}
