// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// FormExtension is an autogenerated mock type for the FormExtension type
type FormExtension struct {
	mock.Mock
}
