// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// FormService is an autogenerated mock type for the FormService type
type FormService struct {
	mock.Mock
}
