// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import context "context"
import http "net/http"
import mock "github.com/stretchr/testify/mock"
import router "flamingo.me/flamingo/v3/framework/router"
import web "flamingo.me/flamingo/v3/framework/web"

// Filter is an autogenerated mock type for the Filter type
type Filter struct {
	mock.Mock
}

// Filter provides a mock function with given fields: ctx, r, w, fc
func (_m *Filter) Filter(ctx context.Context, r *web.Request, w http.ResponseWriter, fc *router.FilterChain) web.Response {
	ret := _m.Called(ctx, r, w, fc)

	var r0 web.Response
	if rf, ok := ret.Get(0).(func(context.Context, *web.Request, http.ResponseWriter, *router.FilterChain) web.Response); ok {
		r0 = rf(ctx, r, w, fc)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(web.Response)
		}
	}

	return r0
}
