// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import web "flamingo.me/flamingo/framework/web"

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// Generate provides a mock function with given fields: session
func (_m *Service) Generate(session *web.Session) string {
	ret := _m.Called(session)

	var r0 string
	if rf, ok := ret.Get(0).(func(*web.Session) string); ok {
		r0 = rf(session)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// IsValid provides a mock function with given fields: request
func (_m *Service) IsValid(request *web.Request) bool {
	ret := _m.Called(request)

	var r0 bool
	if rf, ok := ret.Get(0).(func(*web.Request) bool); ok {
		r0 = rf(request)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}
