// Code generated by mockery v2.12.2. DO NOT EDIT.

package mocks

import (
	testing "testing"

	mock "github.com/stretchr/testify/mock"
)

// Role is an autogenerated mock type for the Role type
type Role struct {
	mock.Mock
}

// Label provides a mock function with given fields:
func (_m *Role) Label() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Permissions provides a mock function with given fields:
func (_m *Role) Permissions() []string {
	ret := _m.Called()

	var r0 []string
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

// NewRole creates a new instance of Role. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewRole(t testing.TB) *Role {
	mock := &Role{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
