// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Role is an autogenerated mock type for the Role type
type Role struct {
	mock.Mock
}

type Role_Expecter struct {
	mock *mock.Mock
}

func (_m *Role) EXPECT() *Role_Expecter {
	return &Role_Expecter{mock: &_m.Mock}
}

// Label provides a mock function with given fields:
func (_m *Role) Label() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Label")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Role_Label_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Label'
type Role_Label_Call struct {
	*mock.Call
}

// Label is a helper method to define mock.On call
func (_e *Role_Expecter) Label() *Role_Label_Call {
	return &Role_Label_Call{Call: _e.mock.On("Label")}
}

func (_c *Role_Label_Call) Run(run func()) *Role_Label_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Role_Label_Call) Return(_a0 string) *Role_Label_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Role_Label_Call) RunAndReturn(run func() string) *Role_Label_Call {
	_c.Call.Return(run)
	return _c
}

// Permissions provides a mock function with given fields:
func (_m *Role) Permissions() []string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Permissions")
	}

	var r0 []string
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

// Role_Permissions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Permissions'
type Role_Permissions_Call struct {
	*mock.Call
}

// Permissions is a helper method to define mock.On call
func (_e *Role_Expecter) Permissions() *Role_Permissions_Call {
	return &Role_Permissions_Call{Call: _e.mock.On("Permissions")}
}

func (_c *Role_Permissions_Call) Run(run func()) *Role_Permissions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Role_Permissions_Call) Return(_a0 []string) *Role_Permissions_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Role_Permissions_Call) RunAndReturn(run func() []string) *Role_Permissions_Call {
	_c.Call.Return(run)
	return _c
}

// NewRole creates a new instance of Role. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRole(t interface {
	mock.TestingT
	Cleanup(func())
}) *Role {
	mock := &Role{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
