// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import context "context"

import mock "github.com/stretchr/testify/mock"
import url "net/url"

// RedirectUrlMaker is an autogenerated mock type for the RedirectUrlMaker type
type RedirectUrlMaker struct {
	mock.Mock
}

// URL provides a mock function with given fields: _a0, _a1
func (_m *RedirectUrlMaker) URL(_a0 context.Context, _a1 string) (*url.URL, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *url.URL
	if rf, ok := ret.Get(0).(func(context.Context, string) *url.URL); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*url.URL)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
