// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	context "context"

	flamingo "flamingo.me/flamingo/v3/framework/flamingo"
	mock "github.com/stretchr/testify/mock"
)

// EventRouter is an autogenerated mock type for the EventRouter type
type EventRouter struct {
	mock.Mock
}

// Dispatch provides a mock function with given fields: ctx, event
func (_m *EventRouter) Dispatch(ctx context.Context, event flamingo.Event) {
	_m.Called(ctx, event)
}
