// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	context "context"

	io "io"

	mock "github.com/stretchr/testify/mock"
)

// TemplateEngine is an autogenerated mock type for the TemplateEngine type
type TemplateEngine struct {
	mock.Mock
}

// Render provides a mock function with given fields: _a0, name, data
func (_m *TemplateEngine) Render(_a0 context.Context, name string, data interface{}) (io.Reader, error) {
	ret := _m.Called(_a0, name, data)

	var r0 io.Reader
	if rf, ok := ret.Get(0).(func(context.Context, string, interface{}) io.Reader); ok {
		r0 = rf(_a0, name, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.Reader)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, interface{}) error); ok {
		r1 = rf(_a0, name, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
