// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// TemplateFunc is an autogenerated mock type for the TemplateFunc type
type TemplateFunc struct {
	mock.Mock
}

// Func provides a mock function with given fields: ctx
func (_m *TemplateFunc) Func(ctx context.Context) interface{} {
	ret := _m.Called(ctx)

	var r0 interface{}
	if rf, ok := ret.Get(0).(func(context.Context) interface{}); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	return r0
}
