package mocks

import mock "github.com/stretchr/testify/mock"

// NonceGenerator is an autogenerated mock type for the NonceGenerator type
type NonceGenerator struct {
	mock.Mock
}

// GenerateNonce provides a mock function with given fields:
func (_m *NonceGenerator) GenerateNonce() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
