package mocks

import mock "github.com/stretchr/testify/mock"
import profiler "flamingo.me/flamingo/framework/profiler"

// Profiler is an autogenerated mock type for the Profiler type
type Profiler struct {
	mock.Mock
}

// Profile provides a mock function with given fields: key, msg
func (_m *Profiler) Profile(key string, msg string) profiler.ProfileFinishFunc {
	ret := _m.Called(key, msg)

	var r0 profiler.ProfileFinishFunc
	if rf, ok := ret.Get(0).(func(string, string) profiler.ProfileFinishFunc); ok {
		r0 = rf(key, msg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(profiler.ProfileFinishFunc)
		}
	}

	return r0
}
